---
index: 0
logging:
  level: info
  file: logs/collector.logs
  syslog: vcap.collector
mbus: nats://uname:pwd@host:port
kairos:
  host: http://kairosdb.ac.crcxnet.com/api/v1/datapoints
  metric_name: cf-collector
intervals:
  discover: 60
  varz: 10
  healthz: 5
  local_metrics: 10
  prune: 300
  nats_ping: 10
deployment_name: CRC-Sweden-CloudFoundry
timestamp: ms
