---
index: 0
logging:
  level: info
  file: /home/ubuntu/collector/logs
  syslog: vcap.collector
mbus: nats://nats:XENcloud123@10.10.15.220:4222
kairos:
  host: http://kairosdb.ac.crcxnet.com/api/v1/datapoints/
  port: 80
  metric-name: cf-collector
intervals:
  discover: 60
  varz: 10
  healthz: 5
  local_metrics: 10
  prune: 300
  nats_ping: 10
